# Generated by Django 2.2.7 on 2019-12-04 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('author', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='_post_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='comments.Posts'),
        ),
    ]
